version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel_boilerplate
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
  laravel-env:
    build: ./dockerfiles
    depends_on:
      - mysql
    volumes:
      - ".:/var/www/laravel-boilerplate"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    expose:
      - "9000"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  nginx:
    image: nginx:latest
    depends_on:
      - laravel-env
    volumes:
      - ".:/var/www/laravel-boilerplate"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - '8080:80'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1